export type ResyRestaurant = {
  name: string;
  neighborhood: string;
  cuisine: string;
  releaseRule: string;
  dropTime: string;
  daysInAdvance?: number;
};

export const resyRestaurants: ResyRestaurant[] = [
  {
    name: "4 Charles Prime Rib",
    neighborhood: "West Village",
    cuisine: "Steakhouse",
    releaseRule: "20 days",
    daysInAdvance: 20,
    dropTime: "9:00 AM",
  },
  {
    name: "Atoboy",
    neighborhood: "NoMad",
    cuisine: "Korean",
    releaseRule: "29 days",
    daysInAdvance: 29,
    dropTime: "12:00 AM",
  },
  {
    name: "Au Cheval",
    neighborhood: "Tribeca",
    cuisine: "American",
    releaseRule: "20 days",
    daysInAdvance: 20,
    dropTime: "9:00 AM",
  },
  {
    name: "Balthazar",
    neighborhood: "Soho",
    cuisine: "French",
    releaseRule: "30 days",
    daysInAdvance: 30,
    dropTime: "12:00 AM",
  },
  {
    name: "Bangkok Supper Club",
    neighborhood: "Meatpacking District",
    cuisine: "Thai",
    releaseRule: "28 days",
    daysInAdvance: 28,
    dropTime: "12:00 AM",
  },
  {
    name: "Bistrot Ha",
    neighborhood: "Lower East Side",
    cuisine: "French Vietnamese",
    releaseRule: "6 days",
    daysInAdvance: 6,
    dropTime: "12:00 AM",
  },
  {
    name: "Bong",
    neighborhood: "Crown Heights",
    cuisine: "Cambodian",
    releaseRule: "19 days",
    daysInAdvance: 19,
    dropTime: "12:00 AM",
  },
  {
    name: "Bonnie's",
    neighborhood: "Williamsburg",
    cuisine: "Cantonese",
    releaseRule: "13 days",
    daysInAdvance: 13,
    dropTime: "10:00 AM",
  },
  {
    name: "Borgo",
    neighborhood: "Flatiron",
    cuisine: "Italian",
    releaseRule: "20 days",
    daysInAdvance: 20,
    dropTime: "10:00 AM",
  },
  {
    name: "Bridges",
    neighborhood: "Chinatown",
    cuisine: "European Bistro",
    releaseRule: "20 days",
    daysInAdvance: 20,
    dropTime: "12:00 PM",
  },
  {
    name: "Bungalow",
    neighborhood: "East Village",
    cuisine: "Indian",
    releaseRule: "20 days",
    daysInAdvance: 20,
    dropTime: "11:00 AM",
  },
  {
    name: "Buvette",
    neighborhood: "West Village",
    cuisine: "French",
    releaseRule: "13 days",
    daysInAdvance: 13,
    dropTime: "10:00 AM",
  },
  {
    name: "Carbone",
    neighborhood: "Greenwich Village",
    cuisine: "Italian",
    releaseRule: "30 days",
    daysInAdvance: 30,
    dropTime: "10:00 AM",
  },
  {
    name: "Chinese Tuxedo",
    neighborhood: "Chinatown",
    cuisine: "Chinese",
    releaseRule: "14 days",
    daysInAdvance: 14,
    dropTime: "12:00 AM",
  },
  {
    name: "Claud",
    neighborhood: "East Village",
    cuisine: "European",
    releaseRule: "15 days",
    daysInAdvance: 15,
    dropTime: "9:00 AM",
  },
  {
    name: "COQODAQ",
    neighborhood: "Flatiron",
    cuisine: "Korean",
    releaseRule: "13 days",
    daysInAdvance: 13,
    dropTime: "10:00 AM",
  },
  {
    name: "Corner Bar",
    neighborhood: "Lower East Side",
    cuisine: "American",
    releaseRule: "31 days",
    daysInAdvance: 31,
    dropTime: "9:00 AM",
  },
  {
    name: "Cote",
    neighborhood: "Chelsea",
    cuisine: "Korean",
    releaseRule: "29 days",
    daysInAdvance: 29,
    dropTime: "10:00 AM",
  },
  {
    name: "Double Chicken Please",
    neighborhood: "Lower East Side",
    cuisine: "Cocktails / New American",
    releaseRule: "6 days",
    daysInAdvance: 6,
    dropTime: "12:00 AM",
  },
  {
    name: "Eleven Madison Park",
    neighborhood: "Flatiron",
    cuisine: "New American",
    releaseRule: "1st of Prev. Month",
    dropTime: "10:00 AM",
  },
  {
    name: "Fish Cheeks",
    neighborhood: "Nolita",
    cuisine: "Thai",
    releaseRule: "29 days",
    daysInAdvance: 29,
    dropTime: "12:00 AM",
  },
  {
    name: "Golden Diner",
    neighborhood: "Chinatown",
    cuisine: "American",
    releaseRule: "29 days",
    daysInAdvance: 29,
    dropTime: "12:00 AM",
  },
  {
    name: "Ha's Snack Bar",
    neighborhood: "Lower East Side",
    cuisine: "Vietnamese",
    releaseRule: "20 days",
    daysInAdvance: 20,
    dropTime: "12:00 PM",
  },
  {
    name: "I Cavallini",
    neighborhood: "Williamsburg",
    cuisine: "Italian",
    releaseRule: "14 days",
    daysInAdvance: 14,
    dropTime: "8:00 AM",
  },
  {
    name: "i Sodi",
    neighborhood: "West Village",
    cuisine: "Italian",
    releaseRule: "13 days",
    daysInAdvance: 13,
    dropTime: "10:00 AM",
  },
  {
    name: "L'Artusi",
    neighborhood: "West Village",
    cuisine: "Italian",
    releaseRule: "14 days",
    daysInAdvance: 14,
    dropTime: "9:00 AM",
  },
  {
    name: "Laser Wolf",
    neighborhood: "Williamsburg",
    cuisine: "Israeli",
    releaseRule: "21 days",
    daysInAdvance: 21,
    dropTime: "10:00 AM",
  },
  {
    name: "Le Café Louis Vuitton",
    neighborhood: "Midtown East",
    cuisine: "French",
    releaseRule: "27 days",
    daysInAdvance: 27,
    dropTime: "12:00 AM",
  },
  {
    name: "Le Chêne",
    neighborhood: "West Village",
    cuisine: "French",
    releaseRule: "14 days",
    daysInAdvance: 14,
    dropTime: "9:00 AM",
  },
  {
    name: "Lei",
    neighborhood: "Chinatown",
    cuisine: "Chinese",
    releaseRule: "13 days",
    daysInAdvance: 13,
    dropTime: "9:00 AM",
  },
  {
    name: "Lilia",
    neighborhood: "Williamsburg",
    cuisine: "Italian",
    releaseRule: "28 days",
    daysInAdvance: 28,
    dropTime: "10:00 AM",
  },
  {
    name: "Masalawala & Sons",
    neighborhood: "Park Slope",
    cuisine: "Indian",
    releaseRule: "14 days",
    daysInAdvance: 14,
    dropTime: "12:00 AM",
  },
  {
    name: "Misi",
    neighborhood: "Williamsburg",
    cuisine: "Italian",
    releaseRule: "27 days",
    daysInAdvance: 27,
    dropTime: "10:00 AM",
  },
  {
    name: "Monkey Bar",
    neighborhood: "Midtown East",
    cuisine: "American",
    releaseRule: "20 days",
    daysInAdvance: 20,
    dropTime: "9:00 AM",
  },
  {
    name: "Peter Luger",
    neighborhood: "Williamsburg",
    cuisine: "Steakhouse",
    releaseRule: "30 days",
    daysInAdvance: 30,
    dropTime: "12:00 AM",
  },
  {
    name: "Ramen by Ra",
    neighborhood: "East Village",
    cuisine: "Japanese",
    releaseRule: "1st & 15th of Month",
    dropTime: "9:00 AM",
  },
  {
    name: "Raoul's",
    neighborhood: "Greenwich Village",
    cuisine: "French",
    releaseRule: "30 days",
    daysInAdvance: 30,
    dropTime: "8:00 AM",
  },
  {
    name: "Rezdôra",
    neighborhood: "Flatiron",
    cuisine: "Italian",
    releaseRule: "29 days",
    daysInAdvance: 29,
    dropTime: "12:00 AM",
  },
  {
    name: "Rubirosa",
    neighborhood: "Nolita",
    cuisine: "Italian",
    releaseRule: "7 days",
    daysInAdvance: 7,
    dropTime: "12:00 AM",
  },
  {
    name: "Sadelle's",
    neighborhood: "Soho",
    cuisine: "Brunch",
    releaseRule: "30 days",
    daysInAdvance: 30,
    dropTime: "10:00 AM",
  },
  {
    name: "schmuck.",
    neighborhood: "East Village",
    cuisine: "Cocktail Bar",
    releaseRule: "14 days",
    daysInAdvance: 14,
    dropTime: "10:00 AM",
  },
  {
    name: "Shuka",
    neighborhood: "Soho",
    cuisine: "Mediterranean",
    releaseRule: "29 days",
    daysInAdvance: 29,
    dropTime: "12:00 AM",
  },
  {
    name: "Sushi Nakazawa",
    neighborhood: "West Village",
    cuisine: "Sushi",
    releaseRule: "14 days",
    daysInAdvance: 14,
    dropTime: "12:00 AM",
  },
  {
    name: "Tatiana",
    neighborhood: "Upper West Side",
    cuisine: "Afro-Caribbean",
    releaseRule: "27 days",
    daysInAdvance: 27,
    dropTime: "12:00 PM",
  },
  {
    name: "Thai Diner",
    neighborhood: "Nolita",
    cuisine: "Thai",
    releaseRule: "7 days",
    daysInAdvance: 7,
    dropTime: "10:00 AM",
  },
  {
    name: "The Four Horsemen",
    neighborhood: "Williamsburg",
    cuisine: "Wine Bar",
    releaseRule: "29 days",
    daysInAdvance: 29,
    dropTime: "7:00 AM",
  },
  {
    name: "The Nines",
    neighborhood: "NoHo",
    cuisine: "American",
    releaseRule: "13 days",
    daysInAdvance: 13,
    dropTime: "12:00 AM",
  },
  {
    name: "Theodora",
    neighborhood: "Fort Greene",
    cuisine: "Mediterranean",
    releaseRule: "30 days",
    daysInAdvance: 30,
    dropTime: "9:00 AM",
  },
  {
    name: "Torrisi Bar & Restaurant",
    neighborhood: "Nolita",
    cuisine: "Italian",
    releaseRule: "30 days",
    daysInAdvance: 30,
    dropTime: "10:00 AM",
  },
  {
    name: "Via Carota",
    neighborhood: "West Village",
    cuisine: "Italian",
    releaseRule: "30 days",
    daysInAdvance: 30,
    dropTime: "10:00 AM",
  },
  {
    name: "Waverly Inn",
    neighborhood: "West Village",
    cuisine: "American",
    releaseRule: "14 days",
    daysInAdvance: 14,
    dropTime: "8:00 AM",
  },
  {
    name: "Yamada",
    neighborhood: "Chinatown",
    cuisine: "Japanese",
    releaseRule: "17 days",
    daysInAdvance: 17,
    dropTime: "12:00 AM",
  },
];
